<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>DiscordBingoBot</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="SourceData\**" />
    <EmbeddedResource Remove="SourceData\**" />
    <None Remove="SourceData\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="font\RobotoMono-VariableFont_wght.ttf" />
    <None Remove="font\RubikMonoOne-Regular.ttf" />
    <None Remove="images\bingocards\0.jpg" />
    <None Remove="images\bingocards\1.jpg" />
    <None Remove="images\bingocards\10.jpg" />
    <None Remove="images\bingocards\11.jpg" />
    <None Remove="images\bingocards\12.jpg" />
    <None Remove="images\bingocards\13.jpg" />
    <None Remove="images\bingocards\2.jpg" />
    <None Remove="images\bingocards\3.jpg" />
    <None Remove="images\bingocards\4.jpg" />
    <None Remove="images\bingocards\5.jpg" />
    <None Remove="images\bingocards\6.jpg" />
    <None Remove="images\bingocards\7.jpg" />
    <None Remove="images\bingocards\8.jpg" />
    <None Remove="images\bingocards\9.jpg" />
    <None Remove="images\icons\ability_demonhunter_darkness.jpg" />
    <None Remove="images\icons\inv_10_alchemy_alchemystone_color4.jpg" />
    <None Remove="images\icons\inv_10_blacksmithing_craftedoptional_engineering_color1.jpg" />
    <None Remove="images\icons\inv_10_engineering_device_gadget1_color1.jpg" />
    <None Remove="images\icons\inv_11_0_arathor_necklace_01_color2.jpg" />
    <None Remove="images\icons\inv_11_0_arathor_ring_01_color2.jpg" />
    <None Remove="images\icons\inv_11_0_dungeon_fancybox_purple.jpg" />
    <None Remove="images\icons\inv_11_0_dungeon_oldgodstatuepiece_purple.jpg" />
    <None Remove="images\icons\inv_11_0_dungeon_tentaclevial_red.jpg" />
    <None Remove="images\icons\inv_11_0_earthen_earthennecklace01_color2.jpg" />
    <None Remove="images\icons\inv_11_0_earthen_earthenring_color2.jpg" />
    <None Remove="images\icons\inv_11_0_earthen_earthenring_color5.jpg" />
    <None Remove="images\icons\inv_11_0_nerubian_necklace_01_color5.jpg" />
    <None Remove="images\icons\inv_11_0_nerubian_ring_01_color4.jpg" />
    <None Remove="images\icons\inv_11_0_nerubian_ring_01_color5.jpg" />
    <None Remove="images\icons\inv_11_0_nerubian_ring_02_color5.jpg" />
    <None Remove="images\icons\inv_11_0_ventureco_ring01_color1.jpg" />
    <None Remove="images\icons\inv_1h_oribosdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_7xp_inscription_talenttome01.jpg" />
    <None Remove="images\icons\inv_achievement_dungeon_rookery.jpg" />
    <None Remove="images\icons\inv_alchemy_70_potion2.jpg" />
    <None Remove="images\icons\inv_arathordungeon_fragment_color2.jpg" />
    <None Remove="images\icons\inv_arathordungeon_fragment_color4.jpg" />
    <None Remove="images\icons\inv_arathordungeon_fragment_color5.jpg" />
    <None Remove="images\icons\inv_arathordungeon_signet_color1.jpg" />
    <None Remove="images\icons\inv_archaeology_70_tauren_moosebonefishhook.jpg" />
    <None Remove="images\icons\inv_argus_ring02.jpg" />
    <None Remove="images\icons\inv_axe_1h_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_axe_1h_kobold_pickaxe_a_01.jpg" />
    <None Remove="images\icons\inv_axe_1h_oribosdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_axe_2h_drustvar_b_01.jpg" />
    <None Remove="images\icons\inv_belt_103.jpg" />
    <None Remove="images\icons\inv_belt_cloth_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_belt_cloth_kultirasdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_belt_leather_kultirasdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_belt_leather_oribosdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_belt_mail_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_belt_mail_kultirasdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_belt_mail_oribosdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_belt_plate_dungeonplate_c_03.jpg" />
    <None Remove="images\icons\inv_belt_plate_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_belt_plate_kultirasdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_boots_mail_dungeonmail_c_03.jpg" />
    <None Remove="images\icons\inv_boots_mail_kultirasdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_boot_cloth_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_boot_cloth_kultirasdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_boot_leather_kultirasdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_boot_leather_oribosdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_boot_mail_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_boot_mail_oribosdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_boot_plate_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_boot_plate_kultirasdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_bow_1h_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_bracer_09.jpg" />
    <None Remove="images\icons\inv_bracer_cloth_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_bracer_cloth_oribosdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_bracer_leather_oribosdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_bracer_mail_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_bracer_mail_kultirasdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_bracer_mail_oribosdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_bracer_plate_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_cape_cloth_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_cape_mail_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_cape_plate_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_chest_cloth_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_chest_leather_31.jpg" />
    <None Remove="images\icons\inv_chest_leather_oribosdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_chest_mail_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_chest_plate_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_crossbow_2h_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_enchanting_70_chaosshard.jpg" />
    <None Remove="images\icons\inv_etherealraid_communicator_color3.jpg" />
    <None Remove="images\icons\inv_firearm_2h_engineering_c_01_blue.jpg" />
    <None Remove="images\icons\inv_firearm_2h_revendrethquest_b_01.jpg" />
    <None Remove="images\icons\inv_gizmo_felironshell.jpg" />
    <None Remove="images\icons\inv_glaive_1h_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_glove_cloth_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_glove_cloth_kultirasdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_glove_cloth_oribosdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_glove_leather_kultirasdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_glove_mail_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_glove_plate_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_glove_plate_kultirasdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_hammer_04.jpg" />
    <None Remove="images\icons\inv_hand_1h_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_helmet_mail_dungeonmail_c_03.jpg" />
    <None Remove="images\icons\inv_helmet_robe_dungeonrobe_c_03.jpg" />
    <None Remove="images\icons\inv_helm_cloth_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_helm_cloth_oribosdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_helm_drustmask_d_01.jpg" />
    <None Remove="images\icons\inv_helm_flowercrown_a_01_orange.jpg" />
    <None Remove="images\icons\inv_helm_leather_oribosdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_helm_mail_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_helm_mail_oribosdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_helm_plate_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_jewelcrafting_70_jeweledlockpick.jpg" />
    <None Remove="images\icons\inv_jewelry_ring_66.jpg" />
    <None Remove="images\icons\inv_knife_1h_cataclysm_c_01.jpg" />
    <None Remove="images\icons\inv_knife_1h_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_knife_1h_earthendungeon_c_02.jpg" />
    <None Remove="images\icons\inv_knife_1h_oribosdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_leather_earthendungeon_c_01_belt.jpg" />
    <None Remove="images\icons\inv_leather_earthendungeon_c_01_boot.jpg" />
    <None Remove="images\icons\inv_leather_earthendungeon_c_01_bracer.jpg" />
    <None Remove="images\icons\inv_leather_earthendungeon_c_01_cape.jpg" />
    <None Remove="images\icons\inv_leather_earthendungeon_c_01_chest.jpg" />
    <None Remove="images\icons\inv_leather_earthendungeon_c_01_glove.jpg" />
    <None Remove="images\icons\inv_leather_earthendungeon_c_01_helm.jpg" />
    <None Remove="images\icons\inv_leather_earthendungeon_c_01_pant.jpg" />
    <None Remove="images\icons\inv_leather_earthendungeon_c_01_shoulder.jpg" />
    <None Remove="images\icons\inv_mace_127.jpg" />
    <None Remove="images\icons\inv_mace_1h_battledungeon_c_02.jpg" />
    <None Remove="images\icons\inv_mace_1h_cataclysm_c_03.jpg" />
    <None Remove="images\icons\inv_mace_1h_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_mace_1h_earthendungeon_c_02.jpg" />
    <None Remove="images\icons\inv_mace_1h_oribosdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_mace_1h_oribosdungeon_c_02.jpg" />
    <None Remove="images\icons\inv_mace_2h_battledungeon_c_01.jpg" />
    <None Remove="images\icons\inv_mace_2h_earthendungeon_c_02.jpg" />
    <None Remove="images\icons\inv_magic_swirl_color3.jpg" />
    <None Remove="images\icons\inv_misc_1h_earthenpitcher_b_01.jpg" />
    <None Remove="images\icons\inv_misc_candlekobold_color1.jpg" />
    <None Remove="images\icons\inv_misc_cape_cataclysm_tank_c_01.jpg" />
    <None Remove="images\icons\inv_misc_cat_trinket09.jpg" />
    <None Remove="images\icons\inv_misc_coinbag07.jpg" />
    <None Remove="images\icons\inv_misc_coin_08.jpg" />
    <None Remove="images\icons\inv_misc_dungeonsignetearthen02_color1.jpg" />
    <None Remove="images\icons\inv_misc_kingsring2.jpg" />
    <None Remove="images\icons\inv_misc_organmass_color2.jpg" />
    <None Remove="images\icons\inv_misc_primitive_toy03.jpg" />
    <None Remove="images\icons\inv_misc_shell_04.jpg" />
    <None Remove="images\icons\inv_misc_spyglass_02.jpg" />
    <None Remove="images\icons\inv_misc_stonering2.jpg" />
    <None Remove="images\icons\inv_misc_whistle_color4.jpg" />
    <None Remove="images\icons\inv_neck_ardenweald_01_silver.jpg" />
    <None Remove="images\icons\inv_nullstone_void.jpg" />
    <None Remove="images\icons\inv_offhand_1h_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_pants_mail_kultirasdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_pants_robe_dungeonrobe_c_03.jpg" />
    <None Remove="images\icons\inv_pant_cloth_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_pant_cloth_kultirasdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_pant_leather_kultirasdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_pant_mail_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_pant_mail_oribosdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_pant_plate_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_pant_plate_kultirasdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_pet_spectralporcupinered.jpg" />
    <None Remove="images\icons\inv_plate_oribosdungeon_c_01_buckle.jpg" />
    <None Remove="images\icons\inv_plate_oribosdungeon_c_01_glove.jpg" />
    <None Remove="images\icons\inv_plate_oribosdungeon_c_01_helm.jpg" />
    <None Remove="images\icons\inv_plate_oribosdungeon_c_01_pants.jpg" />
    <None Remove="images\icons\inv_plate_oribosdungeon_c_01_shoulder.jpg" />
    <None Remove="images\icons\inv_polearm_2h_battledungeon_c_01.jpg" />
    <None Remove="images\icons\inv_polearm_2h_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_polearm_2h_earthendungeon_c_02.jpg" />
    <None Remove="images\icons\inv_polearm_2h_earthendungeon_c_03.jpg" />
    <None Remove="images\icons\inv_raid_creepingcoagulum_blue.jpg" />
    <None Remove="images\icons\inv_raid_mercurialegg_red.jpg" />
    <None Remove="images\icons\inv_ring_80_02a.jpg" />
    <None Remove="images\icons\inv_ring_80_05b.jpg" />
    <None Remove="images\icons\inv_ring_revendreth_01_brown.jpg" />
    <None Remove="images\icons\inv_shield_1h_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_shield_1h_earthendungeon_c_02.jpg" />
    <None Remove="images\icons\inv_shield_1h_oribosdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_shoulder_cloth_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_shoulder_cloth_oribosdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_shoulder_leather_oribosdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_shoulder_mail_dungeonmail_c_03.jpg" />
    <None Remove="images\icons\inv_shoulder_mail_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_shoulder_mail_oribosdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_shoulder_plate_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_staff_2h_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_staff_2h_earthendungeon_c_02.jpg" />
    <None Remove="images\icons\inv_staff_2h_oribosdungeon_c_01.jpg" />
    <None Remove="images\icons\inv_stave_2h_cataclysm_c_02.jpg" />
    <None Remove="images\icons\inv_sword_1h_battledungeon_c_01.jpg" />
    <None Remove="images\icons\inv_sword_1h_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_sword_1h_earthendungeon_c_02.jpg" />
    <None Remove="images\icons\inv_sword_2h_earthendungeon_c_01.jpg" />
    <None Remove="images\icons\inv_wand_1h_cataclysm_c_03.jpg" />
    <None Remove="images\icons\misc_2h_honeydipper_b_01_icon.jpg" />
    <None Remove="images\icons\spell_shadow_gathershadows.jpg" />
    <None Remove="images\icons\spell_shadow_shadowmend.jpg" />
    <None Remove="images\misc\bigx.png" />
    <None Remove="settings.development.json" />
    <None Remove="settings.production.json" />
    <None Remove="tessdata\eng.traineddata" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="font\RobotoMono-VariableFont_wght.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="font\RubikMonoOne-Regular.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\bingocards\0.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\bingocards\1.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\bingocards\10.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\bingocards\11.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\bingocards\12.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\bingocards\13.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\bingocards\2.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\bingocards\3.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\bingocards\4.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\bingocards\5.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\bingocards\6.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\bingocards\7.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\bingocards\8.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\bingocards\9.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\ability_demonhunter_darkness.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_10_alchemy_alchemystone_color4.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_10_blacksmithing_craftedoptional_engineering_color1.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_10_engineering_device_gadget1_color1.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_11_0_arathor_necklace_01_color2.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_11_0_arathor_ring_01_color2.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_11_0_dungeon_fancybox_purple.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_11_0_dungeon_oldgodstatuepiece_purple.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_11_0_dungeon_tentaclevial_red.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_11_0_earthen_earthennecklace01_color2.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_11_0_earthen_earthenring_color2.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_11_0_earthen_earthenring_color5.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_11_0_nerubian_necklace_01_color5.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_11_0_nerubian_ring_01_color4.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_11_0_nerubian_ring_01_color5.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_11_0_nerubian_ring_02_color5.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_11_0_ventureco_ring01_color1.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_1h_oribosdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_7xp_inscription_talenttome01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_achievement_dungeon_rookery.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_alchemy_70_potion2.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_arathordungeon_fragment_color2.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_arathordungeon_fragment_color4.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_arathordungeon_fragment_color5.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_arathordungeon_signet_color1.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_archaeology_70_tauren_moosebonefishhook.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_argus_ring02.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_axe_1h_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_axe_1h_kobold_pickaxe_a_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_axe_1h_oribosdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_axe_2h_drustvar_b_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_belt_103.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_belt_cloth_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_belt_cloth_kultirasdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_belt_leather_kultirasdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_belt_leather_oribosdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_belt_mail_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_belt_mail_kultirasdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_belt_mail_oribosdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_belt_plate_dungeonplate_c_03.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_belt_plate_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_belt_plate_kultirasdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_boots_mail_dungeonmail_c_03.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_boots_mail_kultirasdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_boot_cloth_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_boot_cloth_kultirasdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_boot_leather_kultirasdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_boot_leather_oribosdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_boot_mail_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_boot_mail_oribosdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_boot_plate_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_boot_plate_kultirasdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_bow_1h_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_bracer_09.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_bracer_cloth_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_bracer_cloth_oribosdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_bracer_leather_oribosdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_bracer_mail_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_bracer_mail_kultirasdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_bracer_mail_oribosdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_bracer_plate_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_cape_cloth_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_cape_mail_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_cape_plate_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_chest_cloth_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_chest_leather_31.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_chest_leather_oribosdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_chest_mail_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_chest_plate_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_crossbow_2h_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_enchanting_70_chaosshard.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_etherealraid_communicator_color3.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_firearm_2h_engineering_c_01_blue.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_firearm_2h_revendrethquest_b_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_gizmo_felironshell.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_glaive_1h_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_glove_cloth_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_glove_cloth_kultirasdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_glove_cloth_oribosdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_glove_leather_kultirasdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_glove_mail_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_glove_plate_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_glove_plate_kultirasdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_hammer_04.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_hand_1h_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_helmet_mail_dungeonmail_c_03.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_helmet_robe_dungeonrobe_c_03.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_helm_cloth_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_helm_cloth_oribosdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_helm_drustmask_d_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_helm_flowercrown_a_01_orange.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_helm_leather_oribosdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_helm_mail_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_helm_mail_oribosdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_helm_plate_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_jewelcrafting_70_jeweledlockpick.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_jewelry_ring_66.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_knife_1h_cataclysm_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_knife_1h_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_knife_1h_earthendungeon_c_02.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_knife_1h_oribosdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_leather_earthendungeon_c_01_belt.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_leather_earthendungeon_c_01_boot.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_leather_earthendungeon_c_01_bracer.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_leather_earthendungeon_c_01_cape.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_leather_earthendungeon_c_01_chest.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_leather_earthendungeon_c_01_glove.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_leather_earthendungeon_c_01_helm.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_leather_earthendungeon_c_01_pant.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_leather_earthendungeon_c_01_shoulder.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_mace_127.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_mace_1h_battledungeon_c_02.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_mace_1h_cataclysm_c_03.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_mace_1h_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_mace_1h_earthendungeon_c_02.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_mace_1h_oribosdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_mace_1h_oribosdungeon_c_02.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_mace_2h_battledungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_mace_2h_earthendungeon_c_02.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_magic_swirl_color3.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_misc_1h_earthenpitcher_b_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_misc_candlekobold_color1.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_misc_cape_cataclysm_tank_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_misc_cat_trinket09.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_misc_coinbag07.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_misc_coin_08.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_misc_dungeonsignetearthen02_color1.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_misc_kingsring2.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_misc_organmass_color2.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_misc_primitive_toy03.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_misc_shell_04.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_misc_spyglass_02.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_misc_stonering2.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_misc_whistle_color4.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_neck_ardenweald_01_silver.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_nullstone_void.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_offhand_1h_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_pants_mail_kultirasdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_pants_robe_dungeonrobe_c_03.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_pant_cloth_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_pant_cloth_kultirasdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_pant_leather_kultirasdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_pant_mail_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_pant_mail_oribosdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_pant_plate_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_pant_plate_kultirasdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_pet_spectralporcupinered.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_plate_oribosdungeon_c_01_buckle.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_plate_oribosdungeon_c_01_glove.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_plate_oribosdungeon_c_01_helm.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_plate_oribosdungeon_c_01_pants.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_plate_oribosdungeon_c_01_shoulder.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_polearm_2h_battledungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_polearm_2h_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_polearm_2h_earthendungeon_c_02.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_polearm_2h_earthendungeon_c_03.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_raid_creepingcoagulum_blue.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_raid_mercurialegg_red.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_ring_80_02a.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_ring_80_05b.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_ring_revendreth_01_brown.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_shield_1h_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_shield_1h_earthendungeon_c_02.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_shield_1h_oribosdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_shoulder_cloth_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_shoulder_cloth_oribosdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_shoulder_leather_oribosdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_shoulder_mail_dungeonmail_c_03.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_shoulder_mail_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_shoulder_mail_oribosdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_shoulder_plate_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_staff_2h_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_staff_2h_earthendungeon_c_02.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_staff_2h_oribosdungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_stave_2h_cataclysm_c_02.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_sword_1h_battledungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_sword_1h_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_sword_1h_earthendungeon_c_02.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_sword_2h_earthendungeon_c_01.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\inv_wand_1h_cataclysm_c_03.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\misc_2h_honeydipper_b_01_icon.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\spell_shadow_gathershadows.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\icons\spell_shadow_shadowmend.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\misc\bigx.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="settings.development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="settings.production.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DSharpPlus" Version="5.0.0-nightly-02358" />
    <PackageReference Include="DSharpPlus.Commands" Version="5.0.0-nightly-02358" />
    <PackageReference Include="Hashids.net" Version="1.7.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
    <PackageReference Include="MimeTypes" Version="2.5.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MySqlConnector" Version="2.3.7" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.5" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.4" />
    <PackageReference Include="Tesseract" Version="5.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="tessdata\eng.traineddata">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
